//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tieu_Luan01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIM
    {
        public int MAPHIM { get; set; }
        public string TENPHIM { get; set; }
        public string hinhDD { get; set; }
        public string ndTomTat { get; set; }
        public Nullable<System.DateTime> ngayDang { get; set; }
        public int maLoai { get; set; }
        public string noiDung { get; set; }
        public string taiKhoan { get; set; }
        public string dvt { get; set; }
        public Nullable<bool> daDuyet { get; set; }
        public string nhaSanXuat { get; set; }
        public string daodien { get; set; }
        public string quocgia { get; set; }
        public string dienvien { get; set; }
        public string theloai { get; set; }
        public Nullable<System.DateTime> ngaychieu { get; set; }
    
        public virtual LoaiPhim LoaiPhim { get; set; }
        public virtual TaiKhoan TaiKhoan1 { get; set; }
    }
}
