//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tieu_Luan01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE
    {
        public int MAPHIM { get; set; }
        public string TENPHIM { get; set; }
        public string DiaDiem { get; set; }
        public string hinhDD { get; set; }
        public string ThoiGian { get; set; }
        public int maLoai { get; set; }
        public string NGAYCHIEU { get; set; }
    
        public virtual LoaiPhim LoaiPhim { get; set; }
    }
}
